## Тема “Вычисления с помощью Numpy”

### Задание 1

In [17]:
import numpy as np

In [18]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [55]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

Вариант 1

In [23]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Вариант 2

In [24]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Вариант 1

In [48]:
a_centered_sp = a_centered[:, 0]@a_centered[:, 1]
a_centered_sp

8.0

Вариант 2

In [47]:
a_centered_sp = np.dot(a_centered[:, 0],a_centered[:, 1])
a_centered_sp

8.0

Вариант 3

In [50]:
a_centered_sp = np.inner(a_centered[:, 0],a_centered[:, 1])
a_centered_sp

8.0

In [56]:
N, V = a.shape
cov = a_centered_sp / (N-1)
cov

2.0

### Задание 4

In [61]:
cov = np.cov(a.T)
cov[0,1]

2.0

## Тема “Работа с данными в Pandas”

### Задание 1

In [62]:
import pandas as pd

In [84]:
authors = pd.DataFrame({'author_id' : [1, 2, 3], 
                        'author_name' : ['Тургенев', 'Чехов', 'Островский']})
authors.set_index("author_id", inplace=True)
authors

author_name
author_id            
1            Тургенев
2               Чехов
3          Островский

In [83]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [1000, 1100, 900, 1200, 2000, 1300, 1730]})
books.set_index("author_id", inplace=True)
books

book_title  price
author_id                             
1                   Отцы и дети   1000
1                         Рудин   1100
1             Дворянское гнездо    900
2              Толстый и тонкий   1200
2               Дама с собачкой   2000
3                         Гроза   1300
3          Таланты и поклонники   1730

### Задание 2

In [145]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_name            book_title  price
author_id                                         
1            Тургенев           Отцы и дети   1000
1            Тургенев                 Рудин   1100
1            Тургенев     Дворянское гнездо    900
2               Чехов      Толстый и тонкий   1200
2               Чехов       Дама с собачкой   2000
3          Островский                 Гроза   1300
3          Островский  Таланты и поклонники   1730

### Задание 3

In [106]:
top5 = authors_price.nlargest(5, "price")
top5

author_name            book_title  price
author_id                                         
2               Чехов       Дама с собачкой   2000
3          Островский  Таланты и поклонники   1730
3          Островский                 Гроза   1300
2               Чехов      Толстый и тонкий   1200
1            Тургенев                 Рудин   1100

### Задание 4

In [127]:
authors_stat = authors_price.groupby("author_name").agg({"price":['min', 'max', 'mean']})
authors_stat

price            
              min   max  mean
author_name                  
Островский   1300  1730  1515
Тургенев      900  1100  1000
Чехов        1200  2000  1600

### Задание 5

In [152]:
cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price['cover'] = cover
authors_price

author_name            book_title  price    cover
author_id                                                  
1            Тургенев           Отцы и дети   1000  твердая
1            Тургенев                 Рудин   1100   мягкая
1            Тургенев     Дворянское гнездо    900   мягкая
2               Чехов      Толстый и тонкий   1200  твердая
2               Чехов       Дама с собачкой   2000  твердая
3          Островский                 Гроза   1300   мягкая
3          Островский  Таланты и поклонники   1730   мягкая

In [168]:
book_info = pd.pivot_table(authors_price, 
                           index=["author_name"],
                           values=["price"],
                           columns=["cover"],
                           aggfunc={"price": np.sum},
                           fill_value=0)
book_info

price        
cover       мягкая твердая
author_name               
Островский    3030       0
Тургенев      2000    1000
Чехов            0    3200

In [169]:
book_info.to_pickle("book_info1.pkl")

In [170]:
book_info2 = pd.read_pickle("book_info1.pkl")

In [172]:
book_info == book_info2

price        
cover       мягкая твердая
author_name               
Островский    True    True
Тургенев      True    True
Чехов         True    True